# Chemical Sample Table (CST) Generator

This notebook demonstrates the use of the `create_cst` function to create a Chemical Sample Table from FAIRFluids JSON files.

The function:
- Extracts IUPAC names and CAS Registry Numbers from compounds
- Automatically fetches missing data from PubChem
- Creates an XLSX file with the collected information

In [ ]:
import sys
from pathlib import Path

# Add the main directory to the Python path
project_root = Path().resolve().parent.parent
sys.path.insert(0, str(project_root))

from fairfluids.core.create_cst import create_cst
import pandas as pd

## Example 1: Process a single JSON file

Processes a single JSON file and creates a Chemical Sample Table.

In [ ]:
# Path to the JSON file
json_file = "spera_et_al_fpe_592_2025_114324.json"
output_file = "chemical_sample_table_spera.xlsx"

# Create the Chemical Sample Table
df = create_cst(json_file, output_file)

# Display the first rows
print("\nFirst rows of the Chemical Sample Table:")
print(df.head(10))

Lade spera_et_al_fpe_592_2025_114324.json...
Hole fehlende Daten von PubChem für compound_glycerol (CID: 753)...
Hole fehlende Daten von PubChem für compound_water (CID: 962)...
Hole fehlende Daten von PubChem für compound_carbondioxide (CID: 280)...
Hole fehlende Daten von PubChem für compound_7782447 (CID: 977)...
Hole fehlende Daten von PubChem für compound_cholinechloride (CID: 6209)...

✓ Chemical Sample Table erfolgreich erstellt: chemical_sample_table_spera.xlsx
  Anzahl Verbindungen: 5
  Verbindungen mit IUPAC Name: 5
  Verbindungen mit CAS Registry Number: 5

Erste Zeilen der Chemical Sample Table:
                                  IUPAC Name CAS Registry Number
4  2-hydroxyethyl(trimethyl)azanium chloride             67-48-1
2                             carbon dioxide            124-38-9
3                           molecular oxygen           7782-44-7
1                                    oxidane           7732-18-5
0                        propane-1,2,3-triol             56-81-5

## Example 2: Combine multiple JSON files

Processes multiple JSON files simultaneously and combines all compounds in a single table.

In [ ]:
# List of JSON files
json_files = [
    "spera_et_al_fpe_592_2025_114324.json",
    "Xu_Glycerol_Water.json"
]

output_file = "chemical_sample_table_combined.xlsx"

# Create the combined Chemical Sample Table
df_combined = create_cst(json_files, output_file)

# Display statistics
print("\nStatistics of the combined table:")
print(f"Total number of compounds: {len(df_combined)}")
print(f"\nCompounds with IUPAC Name: {df_combined['IUPAC Name'].notna().sum()}")
print(f"Compounds with CAS Registry Number: {df_combined['CAS Registry Number'].notna().sum()}")
print(f"\nCompounds without IUPAC Name: {df_combined['IUPAC Name'].isna().sum()}")
print(f"Compounds without CAS Registry Number: {df_combined['CAS Registry Number'].isna().sum()}")

# Display the complete table
print("\n\nComplete Chemical Sample Table:")
df_combined

Lade spera_et_al_fpe_592_2025_114324.json...
Lade Xu_Glycerol_Water.json...
Hole fehlende Daten von PubChem für compound_glycerol (CID: 753)...
Hole fehlende Daten von PubChem für compound_water (CID: 962)...
Hole fehlende Daten von PubChem für compound_carbondioxide (CID: 280)...
Hole fehlende Daten von PubChem für compound_7782447 (CID: 977)...
Hole fehlende Daten von PubChem für compound_cholinechloride (CID: 6209)...

✓ Chemical Sample Table erfolgreich erstellt: chemical_sample_table_combined.xlsx
  Anzahl Verbindungen: 5
  Verbindungen mit IUPAC Name: 5
  Verbindungen mit CAS Registry Number: 5

Statistiken der kombinierten Tabelle:
Gesamtanzahl Verbindungen: 5

Verbindungen mit IUPAC Name: 5
Verbindungen mit CAS Registry Number: 5

Verbindungen ohne IUPAC Name: 0
Verbindungen ohne CAS Registry Number: 0


Vollständige Chemical Sample Table:

                                  IUPAC Name CAS Registry Number
4  2-hydroxyethyl(trimethyl)azanium chloride             67-48-1
2                             carbon dioxide            124-38-9
3                           molecular oxygen           7782-44-7
1                                    oxidane           7732-18-5
0                        propane-1,2,3-triol             56-81-5

## Example 3: With additional fields

Creates an extended table with additional information such as Common Name and PubChem ID.

In [ ]:
# Create extended table with additional fields
output_file_extended = "chemical_sample_table_extended.xlsx"

df_extended = create_cst(
    json_files,
    output_file_extended,
    include_additional_fields=True
)

# Display the extended table
print("Extended Chemical Sample Table with additional fields:")
df_extended

Lade spera_et_al_fpe_592_2025_114324.json...
Lade Xu_Glycerol_Water.json...
Hole fehlende Daten von PubChem für compound_glycerol (CID: 753)...
Hole fehlende Daten von PubChem für compound_water (CID: 962)...
Hole fehlende Daten von PubChem für compound_carbondioxide (CID: 280)...
Hole fehlende Daten von PubChem für compound_7782447 (CID: 977)...
Hole fehlende Daten von PubChem für compound_cholinechloride (CID: 6209)...

✓ Chemical Sample Table erfolgreich erstellt: chemical_sample_table_extended.xlsx
  Anzahl Verbindungen: 5
  Verbindungen mit IUPAC Name: 5
  Verbindungen mit CAS Registry Number: 5
Erweiterte Chemical Sample Table mit zusätzlichen Feldern:

,IUPAC Name,CAS Registry Number,Compound ID,Common Name,PubChem ID
4,2-hydroxyethyl(trimethyl)azanium chloride,67-48-1,compound_cholinechloride,Choline Chloride,6209
2,carbon dioxide,124-38-9,compound_carbondioxide,carbon dioxide,280
3,molecular oxygen,7782-44-7,compound_7782447,7782-44-7,977
1,oxidane,7732-18-5,compound_water,water,962
0,"propane-1,2,3-triol",56-81-5,compound_glycerol,glycerol,753

## Example 4: Data analysis

Analyze the created data and display details about missing information.

In [ ]:
# Analyze the data
print("=== Data Analysis ===\n")

# Display compounds without IUPAC Name
missing_iupac = df_extended[df_extended['IUPAC Name'].isna()]
if len(missing_iupac) > 0:
    print(f"Compounds without IUPAC Name ({len(missing_iupac)}):")
    print(missing_iupac[['Compound ID', 'Common Name', 'PubChem ID']])
else:
    print("✓ All compounds have an IUPAC name")

print("\n" + "="*50 + "\n")

# Display compounds without CAS Registry Number
missing_cas = df_extended[df_extended['CAS Registry Number'].isna()]
if len(missing_cas) > 0:
    print(f"Compounds without CAS Registry Number ({len(missing_cas)}):")
    print(missing_cas[['Compound ID', 'Common Name', 'IUPAC Name', 'PubChem ID']])
else:
    print("✓ All compounds have a CAS Registry Number")

print("\n" + "="*50 + "\n")

# Display complete entries
complete = df_extended[
    df_extended['IUPAC Name'].notna() & 
    df_extended['CAS Registry Number'].notna()
]
print(f"Complete entries (with IUPAC Name and CAS Registry Number): {len(complete)}")
if len(complete) > 0:
    print("\nExamples of complete entries:")
    print(complete.head())